services:
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=crud
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    image: node:latest
    working_dir: /app
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:root@mariadb:3306/crud
    command: sh -c "npm install && npm run db:generate && npm run dev"
    depends_on:
      - mariadb

  vite:
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"

  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      MARIADB_ROOT_PASSWORD: root

volumes:
  mariadb_data: